services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
       - '80:80'
    volumes:
       - ./src:/var/www/app
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       - ./nginx/logs:/var/log/nginx
    networks:
       - webnet
    depends_on:
       - php-fpm
       - database
  php-fpm:
     build:
       context: ./php
       dockerfile: Dockerfile
     container_name: php
     ports:
        - '9000:9000'
     volumes:
        - ./src:/var/www/app
     links:
        - database
     networks:
        - webnet

  database:
   image: postgres
   container_name: postgres
   environment:
         POSTGRES_DB: ${DB_DATABASE}
         POSTGRES_USER: ${DB_USERNAME}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
   restart: unless-stopped
   volumes:
        - ./postgres:/var/lib/postgresql
   ports: 
        - "5432:5432"
   networks:
       - webnet
networks:
  webnet:
    driver: bridge